

var states = {
    NONE: 'NONE',
    AWAITING_EMAIL: "AWAITING_EMAIL",
    AWAITING_OTP: "AWAITING_OTP",
    AWAITING_REPEAT_SEND_OTP:'AWAITING_REPEAT_SEND_OTP',
    AWAITING_CHANGE_EMAIL: 'AWAITING_CHANGE_EMAIL',
    AWATING_CODE_TASK: 'AWATING_CODE_TASK',
    AWATING_NUMBER_MONEY_WITHDRAW: 'AWATING_NUMBER_MONEY_WITHDRAW',
    AWATING_INFO_BANKING: 'AWATING_INFO_BANKING',
    AWATING_DATA_TRANSFER_MONEY: 'AWATING_DATA_TRANSFER_MONEY',
}
var stateUsers = {

}



export {
    states,
    stateUsers,
}